services:
  console:
    container_name: trade-gateway-devcontainer
    user: vscode
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    init: true
    volumes:
      - ./:/workspace
      - console-node-modules:/workspace/app/node_modules
      - console-config:/home/vscode/.config
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
      - GOOGLE_CLOUD_PROJECT=trade-gateway
    entrypoint: ["/workspace/console/entrypoint.sh"]
    networks:
      - firebase

  app:
    container_name: trade-gateway-app
    image: node:24-trixie
    volumes:
      - ./app:/app
      - app-node-modules:/app/node_modules
    working_dir: /app
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
      - GOOGLE_CLOUD_PROJECT=trade-gateway
    env_file:
      - ./app/.env
    networks:
      - firebase
    command: bash -c "npm install && npm run dev"

volumes:
  console-config:
  app-node-modules:
  console-node-modules:

networks:
  firebase:
    name: firebase
    external: true
