services:
  console:
    container_name: trade-gateway-devcontainer
    user: vscode
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    init: true
    volumes:
      - ./:/workspace
      - console-node-modules:/workspace/app/node_modules
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
      - GCLOUD_PROJECT="trade-gateway"
    networks:
      - firebase

  app:
    container_name: trade-gateway-app
    image: node:24-trixie
    volumes:
      - ./app:/app
      - app-node-modules:/app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
      - GCLOUD_PROJECT="trade-gateway"
    networks:
      - firebase

volumes:
  app-node-modules:
  console-node-modules:

networks:
  firebase:
    name: firebase
    external: true
