

default:
    @just --choose

test:
    @just check-firebase
    npm run typecheck
    npm run test

# Firebase のヘルスチェック（タイムアウト5秒、失敗したら即終了）
check-firebase:
    @echo "Checking Firebase emulator..."
    @curl --silent --fail --max-time 5 http://${FIRESTORE_EMULATOR_HOST} > /dev/null \
        || (echo "❌ Firebase emulator is not reachable. Please check firebase. Aborting." && exit 1)
    @echo "✅ Firebase is up."

# API をデプロイする
deploy:
    @echo "project = $DEPLOY_GOOGLE_CLOUD_PROJECT"
    @: ${DEPLOY_GOOGLE_CLOUD_PROJECT:?"DEPLOY_GOOGLE_CLOUD_PROJECT が設定されていません。"}
    just build-and-push
    just deploy-from-registry

# API をビルドして Google Container Registry にプッシュする
build-and-push:
    cd ../ && gcloud builds submit . \
        --config api/cloudbuild.yml \
        --project $DEPLOY_GOOGLE_CLOUD_PROJECT

# API を Google Cloud Run にデプロイする
deploy-from-registry:
    gcloud run deploy trade-gateway \
        --project $DEPLOY_GOOGLE_CLOUD_PROJECT \
        --image asia-northeast1-docker.pkg.dev/$DEPLOY_GOOGLE_CLOUD_PROJECT/repos/trade-gateway \
        --region asia-northeast1 \
        --set-secrets "API_SECRET=API_SECRET:latest" \
        --set-secrets "WEBHOOK_SECRET=WEBHOOK_SECRET:latest" \
        --set-secrets "BITFLYER_API_KEY=BITFLYER_API_KEY:latest" \
        --set-secrets "BITFLYER_API_SECRET=BITFLYER_API_SECRET:latest" \
        --set-secrets "SAXO_APP_KEY=SAXO_APP_KEY:latest" \
        --set-secrets "SAXO_APP_SECRET=SAXO_APP_SECRET:latest" \
        --env-vars-file=prod.env.yml \
        --allow-unauthenticated
